import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmsans = DM_Sans({ 
  subsets: ["latin"],
  variable: "--dmsans-font"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dmsans.variable}`}>
      <head>
        {/* Favicon.ico. Add favicon in any sizes */}
        <link rel="icon" href="/favicon.ico" sizes="any" />

        {/* For icon, Support any image types/formats */}
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />

        {/*Apple icon for the apple users */}
      <link
        rel="apple-touch-icon"
        href="/apple-icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />

      </head>
      <body>
        <main className="max-w-6xl mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
